### ISSUE TITLE
`user_country_history` needs to be updated on connect

### ISSUE THREAD

**Issue by peppy** [ppy/osu-server-spectator#228]
```
$countryAcronym = $_SERVER["HTTP_CF_IPCOUNTRY"];

$conn->exec("INSERT INTO user_country_history (user_id, `year_month`, country_acronym) SELECT $userId, date_format(CURRENT_TIMESTAMP, '%y%m'), '{$countryAcronym}' ON DUPLICATE KEY UPDATE count = count + 1");
```

**Comment by bdach** [comment]
To expound on this: the reasoning for doing this is that the table mentioned is what flag change requests are based on. If the lazer client connecting to online systems doesn't result in this being updated anywhere, lazer players will not be offered flag changes.

This is not obvious to do in spectator server due to infrastructural reasons.

@ppy/team-web can you look into the possibility of running the query mentioned above when a user logs in? I had a brief look at how things are structured in web but I don't feel nearly confident enough to be changing stuff in the login flow. I'm not sure on the exact logistics of doing this (should it happen on all logins? only on API sessions initiated via the lazer client?) but I figure you may know what's even _possible_ to do better than I do.

**Comment by nanaya** [comment]
there isn't really a notion of "connect" on the osu-web side. Auth token is only created on first login and the same token/refresh token is reused on future connections without touching the token creation endpoint.

I suppose it could be tacked on as part of `/me` endpoint or something or just every time the api is accessed similar to user last visit update.

**Comment by bdach** [comment]
> I suppose it could be tacked on as part of `/me` endpoint or something or just every time the api is accessed similar to user last visit update.

Seems like a reasonable middle ground, although I'm not sure about the "every time the api is accessed" part - slightly worried about the added db overhead in that case.

> Although I don't know the `count` should be handled in that case (is it even used?)

Good question, I don't think it appears to be...? At least it's not used anywhere in web as far as I can tell.

**Comment by nanaya** [comment]
> Seems like a reasonable middle ground, although I'm not sure about the "every time the api is accessed" part - slightly worried about the added db overhead in that case.

it can be limited to only every five minutes or so, similar to (or more like as part of) last visit update.
